version: "3.7"

services:
  nodejs:
    build:
      context: .
    environment:
      - NODE_ENV=development
    volumes:
      - ../:/usr/src/app
    ports:
      - "3000:3000"
      - "3001:3001"
    # command: sh -c "cd reactapp && npm start"
    tty: true